findComps/urls.py
from django.conf.urls import include, url
from . import views


urlpatterns = [

    url(r'^find/$', views.find, name="find"),
    url(r'^compsearch/$', views.compsearch, name="compsearch")
 ]

maptest/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from maptestapp.views import AccountViewSet

router = routers.SimpleRouter()
router.register(r'accounts', AccountViewSet)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('maptestapp.urls', namespace = "maptestapp")),
    url(r'^findcomps/', include('findComps.urls', namespace="findComps"))
    #url(r'^api/v1/', include(router.urls)),
    #url(r'^$', AccountViewSet.as_view({'get':'list'}), name='index')
]

templates/comps/compResults.html
<html>
{% load staticfiles %}
<body>



{% for key, facility in facility_information.items %}
	<p> {{key}}</p>


	{% for key, value in facility.items %}

		<li>{{key}} -- {{value}}</li>

	{%endfor%}


{%endfor%}



</body>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-98843259-1', 'auto');
  ga('send', 'pageview');

</script>


</html>

templates/comps/findSNFS.html
<html>
{%load staticfiles%}
<!DOCTYPE html>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{%static 'css/comp.css' %}">

<body bgcolor="#375472">
<h1 class="header1"> SKILLED NURSING DATA ENGINE </h1>


<form action = "{% url 'findComps:compsearch' %}" method="POST" id="searchForm" style="width:800px; margin:0 auto;">
								{% csrf_token %}

					<input style="width:800px; margin:0 auto; text-align:center;" type="text" name="subj_addr" placeholder="Enter the full address of subject property.." required>
					<input style="width:800px; margin:0 auto; text-align:center;" type="text" name="zip" placeholder="Enter your zipcode to get started.." required><br>
					<input style="width:800px; margin:0 auto; text-align:center;" type="text" name="radius" placeholder="Enter desired search radius.."required>
					<input style="width:800px; margin:0 auto;" type="submit" id = "searchButton" class="button scrolly" value="Find Care" onclick="loading();">
                  <br>

                <img style="visibility: hidden;  margin:0 auto; display: block; margin-left: auto; margin:-right: auto" src="{%static 'img/loading_neg.gif' %}" id="img" />

        </form>
                  <br>
                  <br>



    </body>

    <script>
            function loading(){
              document.getElementById('img').style.visibility='visible';
            }
    </script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-98843259-1', 'auto');
      ga('send', 'pageview');
    </script>

</html>